# Generated by Django 4.1.7 on 2023-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('product_name', models.TextField()),
                ('price_performance_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('benchmark_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
