# Generated by Django 4.1.7 on 2023-02-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0002_product_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='product_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
