# Generated by Django 4.1.7 on 2023-02-26 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0004_completed_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='timestamp_id',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
