# Generated by Django 4.1.7 on 2023-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0008_productlisting_timestamp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedfetch',
            name='timestamp_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='timestamp_id',
            field=models.BigIntegerField(),
        ),
    ]
