# Generated by Django 4.1.7 on 2023-02-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0009_alter_completedfetch_timestamp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedfetch',
            name='timestamp_id',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='timestamp_id',
        ),
    ]
