# Generated by Django 4.2 on 2023-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0011_completedfetch_timestamp_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
