# Generated by Django 4.2 on 2023-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_fetcher', '0012_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_benchmarks', models.FileField(upload_to='json/')),
                ('cpu_g_benchmarks', models.FileField(upload_to='json/')),
                ('cpu_n_benchmarks', models.FileField(upload_to='json/')),
            ],
        ),
    ]
