// import './globals.css'
import Link from "next/link";
import "@picocss/pico/css/pico.min.css";
// import "../app/css/custom.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <main className="container">
          <nav>
            <Link href="/">Home</Link>
            <Link href="/fetches">Completed Price Fetches</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
