export const gpuInfo = {
  "GeForce RTX 4090": {
    tier: "1",
    manufacturer: "Nvidia",
    cssName: "rtx-4090",
  },
  "GeForce RTX 4080": {
    tier: "1",
    manufacturer: "Nvidia",
    cssName: "rtx-4080",
  },
  "Radeon RX 7900 XTX": {
    tier: "1",
    manufacturer: "AMD",
    cssName: "rx-7900-xtx",
  },
  "GeForce RTX 4070 Ti": {
    tier: "2",
    manufacturer: "Nvidia",
    cssName: "rtx-4070-ti",
  },
  "Radeon RX 6950 XT": {
    tier: "2",
    manufacturer: "AMD",
    cssName: "rx-6950-xt",
  },
  "Radeon RX 7900 XT": {
    tier: "2",
    manufacturer: "AMD",
    cssName: "rx-7900-xt",
  },
  "Radeon RX 6800 XT": {
    tier: "2",
    manufacturer: "AMD",
    cssName: "rx-6800-xt",
  },
  "GeForce RTX 3070 Ti": {
    tier: "3",
    manufacturer: "Nvidia",
    cssName: "rtx-3070-ti",
  },
  "GeForce RTX 3070": {
    tier: "3",
    manufacturer: "Nvidia",
    cssName: "rtx-3070",
  },
  "Radeon RX 6800": {
    tier: "3",
    manufacturer: "AMD",
    cssName: "rx-6800",
  },
  "Radeon RX 6750 XT": {
    tier: "3",
    manufacturer: "AMD",
    cssName: "rx-6750-xt",
  },
  "GeForce RTX 3060 Ti": {
    tier: "4",
    manufacturer: "Nvidia",
    cssName: "rtx-3060-ti",
  },
  "Radeon RX 6700 XT": {
    tier: "4",
    manufacturer: "AMD",
    cssName: "rx-6700-xt",
  },
  "Radeon RX 6700": {
    tier: "4",
    manufacturer: "AMD",
    cssName: "rx-6700",
  },
  "Radeon RX 6650 XT": {
    tier: "4",
    manufacturer: "AMD",
    cssName: "rx-6650-xt",
  },
  "GeForce RTX 3060": {
    tier: "5",
    manufacturer: "Nvidia",
    cssName: "rtx-3060",
  },
  "Radeon RX 6600 XT": {
    tier: "5",
    manufacturer: "AMD",
    cssName: "rx-6600-xt",
  },
  "Radeon RX 6600": {
    tier: "5",
    manufacturer: "AMD",
    cssName: "rx-6600",
  },
  "GeForce RTX 2060": {
    tier: "6",
    manufacturer: "Nvidia",
    cssName: "rtx-2060",
  },
  "GeForce GTX 1660 Super": {
    tier: "6",
    manufacturer: "Nvidia",
    cssName: "gtx-1660-super",
  },
  "GeForce RTX 3050": {
    tier: "6",
    manufacturer: "Nvidia",
    cssName: "rtx-3050",
  },
  "GeForce GTX 1660 Ti": {
    tier: "6",
    manufacturer: "Nvidia",
    cssName: "gtx-1660-ti",
  },
  "GeForce GTX 1660": {
    tier: "7",
    manufacturer: "Nvidia",
    cssName: "gtx-1660",
  },
  "Radeon RX 6500 XT": {
    tier: "7",
    manufacturer: "AMD",
    cssName: "rx-6500-xt",
  },
  "Radeon RX 6400": {
    tier: "7",
    manufacturer: "AMD",
    cssName: "rx-6400",
  },
};

export const cpuInfo = {
  "AMD Ryzen 9 7950X3D": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7950x3d",
  },
  "AMD Ryzen 9 7900X3D": {
    gamingTier: "1",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7900x3d",
  },
  "AMD Ryzen 7 7800X3D": {
    gamingTier: "1",
    normalTier: "4",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7800x3d",
  },
  "AMD Ryzen 9 5950X": {
    gamingTier: "6",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5950x",
  },
  "AMD Ryzen 9 5900X": {
    gamingTier: "5",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5900x",
  },
  "AMD Ryzen 7 5800X": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5800x",
  },
  "AMD Ryzen 7 5800X3D": {
    gamingTier: "1",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5800x3d",
  },
  "AMD Ryzen 7 5700X": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5700x",
  },
  "AMD Ryzen 5 5600X": {
    gamingTier: "5",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5600x",
  },
  "AMD Ryzen 5 5600": {
    gamingTier: "5",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5600",
  },
  "AMD Ryzen 5 5500": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
    cssName: "amd-5500",
  },
  "AMD Ryzen 9 7950X": {
    gamingTier: "3",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7950x",
  },
  "AMD Ryzen 9 7900X": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7900x",
  },
  "AMD Ryzen 9 7900": {
    gamingTier: "7",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7900",
  },
  "AMD Ryzen 7 7700X": {
    gamingTier: "3",
    normalTier: "4",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7700x",
  },
  "AMD Ryzen 7 7700": {
    gamingTier: "7",
    normalTier: "4",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7700",
  },
  "AMD Ryzen 5 7600X": {
    gamingTier: "2",
    normalTier: "6",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7600x",
  },
  "AMD Ryzen 5 7600": {
    gamingTier: "2",
    normalTier: "6",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
    cssName: "amd-7600",
  },
  "Intel Core i9-13900KS": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13900ks",
  },
  "Intel Core i9-13900K": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13900k",
  },
  "Intel Core i9-13900KF": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13900kf",
  },
  "Intel Core i9-13900F": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13900f",
  },
  "Intel Core i9-13900": {
    gamingTier: "",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13900",
  },
  "Intel Core i7-13700K": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13700k",
  },
  "Intel Core i7-13700KF": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13700kf",
  },
  "Intel Core i9-12900KS": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12900ks",
  },
  "Intel Core i9-12900K": {
    gamingTier: "3",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12900k",
  },
  "Intel Core i9-12900KF": {
    gamingTier: "3",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12900kf",
  },
  "Intel Core i7-13700": {
    gamingTier: "3",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13700",
  },
  "Intel Core i7-13700F": {
    gamingTier: "3",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13700f",
  },
  "Intel Core i5-13600K": {
    gamingTier: "2",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13600k",
  },
  "Intel Core i5-13600KF": {
    gamingTier: "2",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13600kf",
  },
  "Intel Core i9-12900F": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12900f",
  },
  "Intel Core i9-12900": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12900",
  },
  "Intel Core i7-12700K": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12700k",
  },
  "Intel Core i7-12700KF": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12700kf",
  },
  "Intel Core i5-13500": {
    gamingTier: "4",
    normalTier: "5",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13500",
  },
  "Intel Core i7-12700F": {
    gamingTier: "5",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12700f",
  },
  "Intel Core i7-12700": {
    gamingTier: "5",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12700",
  },
  "Intel Core i5-12600K": {
    gamingTier: "4",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12600k",
  },
  "Intel Core i5-12600KF": {
    gamingTier: "4",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12600kf",
  },
  "Intel Core i5-13400": {
    gamingTier: "5",
    normalTier: "6",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13400",
  },
  "Intel Core i5-13400F": {
    gamingTier: "5",
    normalTier: "6",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-13400f",
  },
  "Intel Core i5-12600": {
    gamingTier: "5",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12600",
  },
  "Intel Core i5-12500": {
    gamingTier: "6",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12500",
  },
  "Intel Core i5-12400F": {
    gamingTier: "6",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12400f",
  },
  "Intel Core i5-12400": {
    gamingTier: "6",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
    cssName: "intel-12400",
  },
};
