// Information about every GPU and CPU model available in this app
export const gpuInfo = {
  "GeForce RTX 4090": {
    tier: "1",
    manufacturer: "Nvidia",
  },
  "GeForce RTX 4080": {
    tier: "1",
    manufacturer: "Nvidia",
  },
  "GeForce RTX 4080 Super": {
    tier: "1",
    manufacturer: "Nvidia",
  },
  "GeForce RTX 4070 Ti Super": {
    tier: "2",
    manufacturer: "Nvidia",
  },
  "GeForce RTX 4070 Super": {
    tier: "3",
    manufacturer: "Nvidia",
  },
  "Radeon RX 7900 XTX": {
    tier: "2",
    manufacturer: "AMD",
  },
  "GeForce RTX 4070 Ti": {
    tier: "2",
    manufacturer: "Nvidia",
  },
  "Radeon RX 6950 XT": {
    tier: "3",
    manufacturer: "AMD",
  },
  "Radeon RX 7900 XT": {
    tier: "2",
    manufacturer: "AMD",
  },
  "Radeon RX 7900 GRE": {
    tier: "3",
    manufacturer: "AMD",
  },
  "Radeon RX 6800 XT": {
    tier: "4",
    manufacturer: "AMD",
  },
  "GeForce RTX 4070": {
    tier: "4",
    manufacturer: "Nvidia",
  },
  "Radeon RX 7800 XT": {
    tier: "4",
    manufacturer: "AMD",
  },
  "GeForce RTX 4060 Ti": {
    tier: "5",
    manufacturer: "Nvidia",
  },
  "Radeon RX 6750 XT": {
    tier: "5",
    manufacturer: "AMD",
  },
  "Radeon RX 7700 XT": {
    tier: "4",
    manufacturer: "AMD",
  },
  "GeForce RTX 3060 Ti": {
    tier: "5",
    manufacturer: "Nvidia",
  },
  "Radeon RX 6700 XT": {
    tier: "5",
    manufacturer: "AMD",
  },
  "GeForce RTX 4060": {
    tier: "6",
    manufacturer: "Nvidia",
  },
  "Radeon RX 7600": {
    tier: "6",
    manufacturer: "AMD",
  },
  "Radeon RX 6650 XT": {
    tier: "6",
    manufacturer: "AMD",
  },
  "GeForce RTX 3060": {
    tier: "6",
    manufacturer: "Nvidia",
  },
  "Radeon RX 6600 XT": {
    tier: "6",
    manufacturer: "AMD",
  },
  "Radeon RX 6600": {
    tier: "7",
    manufacturer: "AMD",
  },
  "GeForce GTX 1660 Super": {
    tier: "7",
    manufacturer: "Nvidia",
  },
  "GeForce RTX 3050": {
    tier: "7",
    manufacturer: "Nvidia",
  },
  "Intel Arc B580": {
    tier: "7",
    manufacturer: "Intel",
  },
};

export const cpuInfo = {
  "AMD Ryzen 7 9800X3D": {
    gamingTier: "1",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 9950X": {
    gamingTier: "3",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 9900X": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 7 9700X": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 5 9600X": {
    gamingTier: "3",
    normalTier: "5",
    generation: "Latest Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 7950X3D": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 7900X3D": {
    gamingTier: "1",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 7 7800X3D": {
    gamingTier: "1",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 5950X": {
    gamingTier: "7",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 9 5900X": {
    gamingTier: "5",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 7 5800X": {
    gamingTier: "7",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 7 5700X": {
    gamingTier: "7",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 7 5700X3D": {
    gamingTier: "2",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 7 5700": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 5 5600X": {
    gamingTier: "6",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 5 5600": {
    gamingTier: "6",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 5 5500": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM4",
  },
  "AMD Ryzen 9 7950X": {
    gamingTier: "4",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 7900X": {
    gamingTier: "3",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 9 7900": {
    gamingTier: "3",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 7 7700X": {
    gamingTier: "5",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 7 7700": {
    gamingTier: "5",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 5 7600X": {
    gamingTier: "4",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "AMD Ryzen 5 7600": {
    gamingTier: "5",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "AMD",
    socket: "Socket AM5",
  },
  "Intel Core Ultra 9 285K": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1851",
  },
  "Intel Core Ultra 7 265K": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1851",
  },
  "Intel Core Ultra 7 265KF": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1851",
  },
  "Intel Core Ultra 5 245K": {
    gamingTier: "1",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1851",
  },
  "Intel Core Ultra 5 245KF": {
    gamingTier: "1",
    normalTier: "3",
    generation: "Latest Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1851",
  },
  "Intel Core i9-14900KS": {
    gamingTier: "1",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-14900K": {
    gamingTier: "2",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-14900KF": {
    gamingTier: "2",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-14900F": {
    gamingTier: "3",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-14900": {
    gamingTier: "3",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-14700K": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-14700KF": {
    gamingTier: "2",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-14700F": {
    gamingTier: "4",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-14700": {
    gamingTier: "4",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14600K": {
    gamingTier: "3",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14600KF": {
    gamingTier: "3",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14600": {
    gamingTier: "7",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14500": {
    gamingTier: "5",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14400F": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-14400": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-13900KS": {
    gamingTier: "2",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-13900K": {
    gamingTier: "2",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-13900KF": {
    gamingTier: "2",
    normalTier: "1",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-13900F": {
    gamingTier: "3",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-13900": {
    gamingTier: "4",
    normalTier: "2",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-13700K": {
    gamingTier: "4",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-13700KF": {
    gamingTier: "3",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-12900KS": {
    gamingTier: "4",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-12900K": {
    gamingTier: "5",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-12900KF": {
    gamingTier: "5",
    normalTier: "3",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-13700": {
    gamingTier: "5",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-13700F": {
    gamingTier: "5",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-13600K": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-13600KF": {
    gamingTier: "4",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-12900F": {
    gamingTier: "6",
    normalTier: "4",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i9-12900": {
    gamingTier: "6",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-12700K": {
    gamingTier: "6",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-12700KF": {
    gamingTier: "6",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-13500": {
    gamingTier: "5",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-12700F": {
    gamingTier: "7",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i7-12700": {
    gamingTier: "7",
    normalTier: "5",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12600K": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12600KF": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-13400": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-13400F": {
    gamingTier: "6",
    normalTier: "6",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12600": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12500": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12400F": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
  "Intel Core i5-12400": {
    gamingTier: "7",
    normalTier: "7",
    generation: "Previous Generation",
    manufacturer: "Intel",
    socket: "Socket LGA 1700",
  },
};
